GET http://127.0.0.1:8000/api/songs/ HTTP/1.1
x-auth-token: xeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk1YzQ0NjVkMzgwM2UwZmI3NGU1ZmYiLCJuYW1lIjoiYWRtaW4iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzA3NjMzMTEsImV4cCI6MTY3MTM2ODExMX0.Xqw-arao5Fsy2TdCAkQhEUG6bMJm4cWBYj2Sgn3Ykhg
