GET http://127.0.0.1:8000/api/songs/like HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk1ZjNlYmUyMzQzM2RhZjE0YzYwYjgiLCJuYW1lIjoidGVzdCB1c2VyIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MDc4MTMyOSwiZXhwIjoxNjcxMzg2MTI5fQ.9RW-tzLlKK9ZVu0AkJCf5ZokiXvlK5Go_26cXJLu6Fg
