GET http://127.0.0.1:8000/api/users/6395f3ebe23433daf14c60b8 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk1YzQ0NjVkMzgwM2UwZmI3NGU1ZmYiLCJuYW1lIjoiYWRtaW4iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzA3Nzg4MzQsImV4cCI6MTY3MTM4MzYzNH0.XfIAg10-u4GiklAAKipcfxXU2KND8709MZpDB6Iejy8
